### ISSUE TITLE
Error when you include MaxNWts argument in mice() call and use mice.impute.cart somewhere in the model

### ISSUE THREAD

**Issue by wepelham3** [stefvanbuuren/mice#13]
I often end up having to use the `MaxNWts` argument in the `mice` call when using the `polyreg` imputation method, as described [here](http://stackoverflow.com/questions/28551633/error-in-r-mice-package-too-many-weights).  Like so:

```r
df.imputed = mice(data = df.to.impute, m = 5, maxit = 10, MaxNWts = 5000)
```

However, if the same model **also** uses the `cart` imputation method, then the following error will be thrown when that `MaxNWts` argument gets passed to `rpart()` in `mice.impute.cart.r`...

```r
Error in rpart(yobs ~ ., data = cbind(yobs, xobs), method = "anova", control = rpart.control(minbucket = minbucket,  : 
  Argument MaxNWts not matched
```

Thus it does not seem currently possible to use **both** the `polr` method and the `cart` method in the same imputation model when you need to increase the number of maximum weights.  Is there a simple workaround?

**Comment by stefvanbuuren** [comment]
Thanks. It’s a curious error. The dots argument in rpart() should accept any name, so I do not know why you get this error.

Some approaches:

-          Try to simplify your imputation model by eliminating factor with many categories, or use pmm for these variables, so that you don’t need MaxNWts;

-          Or, make your own version of mice.impute.cart() with the dots argument deleted everywhere;

-          Or, go down to see why rpart() or rpart.control() won’t accept the name (there might be a good reason for it).

Hope this helps.

Van: wepelham3 <notifications@github.com>
Beantwoorden - Aan: stefvanbuuren/mice <reply@reply.github.com>
Datum: donderdag 15 september 2016 20:23
Aan: stefvanbuuren/mice <mice@noreply.github.com>
Onderwerp: [stefvanbuuren/mice] Error when you include MaxNWts argument in mice() call and use mice.impute.cart somwhere in the model (#13)


I often end up having to use the MaxNWts argument in the mice call when using the polyreg imputation method, as described here<http://stackoverflow.com/questions/28551633/error-in-r-mice-package-too-many-weights>. Like so:

df.imputed = mice(data = df.to.impute, m = 5, maxit = 10, MaxNWts = 5000)

However, if the same model also uses the cart imputation method, then the following error will be thrown when that MaxNWts argument gets passed to rpart() in mice.impute.cart.r...

Error in rpart(yobs ~ ., data = cbind(yobs, xobs), method = "anova", control = rpart.control(minbucket = minbucket,  :

  Argument MaxNWts not matched

Thus it does not seem currently possible to use both the polr method and the cart method in the same imputation model when you need to increase the number of maximum weights. Is there a simple workaround?

**Comment by stefvanbuuren** [comment]
Moved dots argument to rpart.control(). Can you test whether it works now?

devtools::install_github("stefvanbuuren/mice@rpartdots")


Van: wepelham3 <notifications@github.com>
Beantwoorden - Aan: stefvanbuuren/mice <reply@reply.github.com>
Datum: donderdag 15 september 2016 20:23
Aan: stefvanbuuren/mice <mice@noreply.github.com>
Onderwerp: [stefvanbuuren/mice] Error when you include MaxNWts argument in mice() call and use mice.impute.cart somwhere in the model (#13)


I often end up having to use the MaxNWts argument in the mice call when using the polyreg imputation method, as described here<http://stackoverflow.com/questions/28551633/error-in-r-mice-package-too-many-weights>. Like so:

df.imputed = mice(data = df.to.impute, m = 5, maxit = 10, MaxNWts = 5000)

However, if the same model also uses the cart imputation method, then the following error will be thrown when that MaxNWts argument gets passed to rpart() in mice.impute.cart.r...

Error in rpart(yobs ~ ., data = cbind(yobs, xobs), method = "anova", control = rpart.control(minbucket = minbucket,  :

  Argument MaxNWts not matched

Thus it does not seem currently possible to use both the polr method and the cart method in the same imputation model when you need to increase the number of maximum weights. Is there a simple workaround?

**Comment by stefvanbuuren** [comment]
Now in V2.28
