### ISSUE TITLE
pool() fails when no "glance" method is available

### ISSUE THREAD

**Issue by clbustos** [stefvanbuuren/mice#142]
On new mice version, pool.fitlist lookup for glance method on all models. I pool the results of multiple glht models; although they have correct coef() and vcov() methods, pool fails. 
 It would be great to just bypass methods without broom support, to allow old scripts works.

Thanks

**Comment by stefvanbuuren** [comment]
I am a little hesitant to put that back in. Package authors have implemented `coef()` and `vcov()` in many different ways. In the past, I got many questions of the type "my `vcov` does not work", and I have no wish to receive those question again. 

The `broom` package is a generic solution for integrating packages, and the preferred way of running your analysis would be to write a few plug-in functions so that the `broom` package understands `glht` models.

**Comment by clbustos** [comment]
Thanks for your explanation. I will look into broom to understand how it works.
