### ISSUE TITLE
Diagnostic plots for logical values

### ISSUE THREAD

**Issue by lillemets** [stefvanbuuren/mice#155]
I'm unable to create plots for class `mids` objects using `densityplot`, `stripplot` or `bwplot` because the `mids` object contains imputed logical values.

```
Error in bind_rows_(x, .id) : 
  Column `variablename` can't be converted from logical to numeric
```

Is this expected behavior? Is there a solution?

**Comment by stefvanbuuren** [comment]
These `lattice` functions are for numeric outcomes. One way to circumvent the error is to manually convert `logical` by `as.numeric` before imputation, and use the default imputation method (`pmm`) for these variables. However, the resulting plots might not make much sense since there are only two different values.
