### ISSUE TITLE
grep() in mice:::check.predictorMatrix()

### ISSUE THREAD

**Issue by maciejrosolowski** [stefvanbuuren/mice#156]
Using `grep()` for setting the diagonal of the predictorMatrix to 0 (code copied from `mice:::check.predictorMatrix()`):

```{r}
for (i in row.names(predictorMatrix)) predictorMatrix[i, grep(i, colnames(predictorMatrix))] <- 0
```

has the consequence that entries of variables with similar names will be set to 0 as well. For example, if a variable's name is "LAC" and another variable's name is "LAC_V2" than not only the entries on the diagonal will be set to 0 but also the entries `predictorMatrix[ "LAC", "LAC_V2"]` and `predictorMatrix[ "LAC_V2", "LAC"]`. This is probably not intended.

**Comment by stefvanbuuren** [comment]
Ah, thanks. This could be very well the cause of the naming problem discussed in #149.

**Comment by stefvanbuuren** [comment]
Von: König, Dr. Jochem
Gesendet: Sonntag, 2. Dezember 2018 15:15:23
An: s.vanbuuren@uu.nl
Cc: Schlecht, Jennifer; Wollschlaeger, Daniel
Betreff: Some strange behaviour of mice passive imputation

Dear Stef van Buuren,

we have detected some strange behaviour of mice package’s passive imputation feature.

If some variable name is the prefix of another variable, it does not work. See the following example:

```{r}
# Example passive imputation with mice
var1=c(NA,rnorm(7));var2=c(rnorm(7),NA);var3=var1+var2;var3[1:4]<-NA;
d<-data.frame(var1,var2,var3)
ini <- mice(d, maxit=0, print=F); meth<- ini$meth; pred <- ini$pred
pred[1:2, 3] <- 0;meth[3]<- "~I(var1 + var2)"
dimp <- mice(d, meth=meth, pred=pred, seed=123, print=F)
d1<-complete(dimp);cbind(d1,d1$var1+d1$var2)

# Problem with passive imputation if dependent variable name is prefix of some other variable:
names(d)[3]<-"var";names(meth)[3]<-"var";rownames(pred)[3]<-"var"; colnames(pred)[3]<-"var";
dimp <- mice(d, meth=meth, pred=pred, seed=123, print=F)
d2<-complete(dimp); cbind(d2,d2$var1+d2$var2)
```

The problem stated here: https://github.com/stefvanbuuren/mice/issues/147
may be of similar character.

Unfortunately, I am not an experienced github user. Hence I could figure out how to leave this message via github.

Kind regards,

Jochem König

**Comment by stefvanbuuren** [comment]
The problem seems to be due to the changes to the predictorMatrix introduced in check.predictorMatrix(), file predictorMatrix.R, line 49-50:

```r
for (i in row.names(predictorMatrix)) predictorMatrix[i,
            grep(i, colnames(predictorMatrix))] <- 0
```

The problem is that with column names "var1", "var2", "var" and "i" set to "var", `grep(i, colnames(predictorMatrix))` by default returns "1 2 3" instead of just "3" because the pattern "var" is treated as a regular expression.

To enable exact matching, one can use `grep(i, colnames(predictorMatrix), fixed=TRUE)` if that is intended here.

BTW, many thanks for developing mice and making it freely available! We have used it a number of times for published research.

Best regards

Daniel Wollschlaeger

**Comment by stefvanbuuren** [comment]
Thanks maciejrosolowski, Jochem and Daniel.

I just pushed version `mice 3.3.4`, which should solve this.
