### ISSUE TITLE
Typo in multilevel vignette

### ISSUE THREAD

**Issue by markseeto** [stefvanbuuren/mice#167]
In Step 24, `meth <- c("", "", "2l.norm", "logreg", "2lonly.mean2", "2l.pan", "2l.pan")` has `2lonly.mean2`, which I assume should be `2lonly.mean`.

**Comment by gerkovink** [comment]
Dear Mark, 

This is not a typo; the `popular.RData` workspace contains a function named `mice.impute.2lonly.mean2`. It is this function that is called in the example:
```r
> load("popular.RData")
> ls()
[1] "icc"                      "mice.impute.2lonly.mean2" "popMCAR"                 
[4] "popMCAR2"                 "popNCR"                   "popNCR2"                 
[7] "popNCR3"                  "popular"    
```

 However, you are correct that the `mice.impute.2lonly.mean()` function could also be used. The result of both functions would be equivalent, however, the current `mice.impute.2lonly.mean()` fits seamlessly into the new `mice 3+` environment, while the side loaded `mice.impute.2lonly.mean2()` from the vignette does not. 

This issue has been fixed in gerkovink/miceVignettes#1. 

Thanks for letting me know. 

All the best, 

Gerko
