### ISSUE TITLE
Error in mice() - arguments imply differing number of rows

### ISSUE THREAD

**Issue by byapparov** [stefvanbuuren/mice#168]
I was trying to use `mice()` to answer [this](https://stackoverflow.com/questions/55092609/how-to-write-a-function-that-imputes-missing-numeric-and-character-values) question, but could not impute data for some reason:

```R
dt = read.table(
  textConnection("ID GLUC TGL HDL LDL HRT MAMM SMOKE
A   88   NA  32  99   Y   NA never
B   NA   150 60  NA  NA   no never
C   110   NA NA 120   N   NA    NA
D   NA   200 65 165  NA  yes never"),  header = TRUE)

res <- mice(dt)

# Error in data.frame(it = s$it, im = s$im, dep = s$dep, meth = if (is.null(meth)) s$meth else meth,  : 
#  arguments imply differing number of rows: 0, 1
```

**Comment by stefvanbuuren** [comment]
I wasn't able to reproduce in `mice 3.4.0`. `mice` imputes `HDL`, and removes the other variables due to constant and multicollinearity problems. I tried seed values `1:10`, and these all produced an output. 

It seems that your run also throws out the last variable `HDL`, but I reproduce that this happens.

**Comment by stefvanbuuren** [comment]
Closed because `mice` seems to behave as expected.
