### ISSUE TITLE
mice.impute.polr seems to always fall back to multinom

### ISSUE THREAD

**Issue by simon-r-white** [stefvanbuuren/mice#206]
When using the mice.impute.polr() function, within the sampler.univ() makes a call to do.call().

Within the list of arguments is a "type" entry, which I believe causes polr() to fail - using traceback() it seems to keep falling over when passing the ''...'' down the function stack to optim().

````
Error in fn(par, ...) :
   unused argument (type = c(1, 1, 1, 1, 1, 1, 1, 1))
````

So the polr() call fails, which triggers the fall back to multinom().

The documentation says this should be flagged in the loggedEvents, but it is not.

Thus, I believe the mice.impute.polr() actually always silently falls back to using multinom().

**Comment by stefvanbuuren** [comment]
What a great find. 

I can confirm that for versions `mice 3.0.0` to `mice 3.6.6` any method requests for `polr` were in fact handled by `multinom`. This may occasionally also have happened in earlier version of `mice`,  in particular in cases where the user specified additional arguments that were passed down over the dots. 

The fix relocates the dots argument in the call to `polr()` to `control = list(...)`. In this way, the user is still able to influence the inner workings of `polr()`by setting arguments in the `control` list.

In addition, `polr()` failures can now be printed to `loggedEvents`. By default, fallback to `multinom()` is not printed (because there can be many, which is distracting), but the user can set `mice(data, polr.to.loggedEvents = TRUE)` to switch on these warnings.
