### ISSUE TITLE
predictorMatrix is automatically modified by mice

### ISSUE THREAD

**Issue by Bigsealion** [stefvanbuuren/mice#234]
When I use mice to make mulitiple imputation, some col will not be contain in predictmatrix automatically. In the predictmatrix, related row and col be set 0. Even I set the parameter 'predictmatrix' in function 'mice', this col and row will be 0 automatically again.
I find this col is  highly correlated to some other column(r>0.99). Could this be the cause of the problem?
How can I set it in imputation?

**Comment by stefvanbuuren** [comment]
`mice` pre-processes the data and the model in order to evade problems later on. Inspect `imp$loggedEvents` to see what happened in your case. 

The checks are there for a reason. But if you really insist on imputing duplicate and/or linearly dependent column you can tweak things with  `eps` or `maxcor`. *Danger*: These options are only for users who are able to predict the consequences.

**Comment by stefvanbuuren** [comment]
No reprex, so I am closing. Please feel free to reopen with a reprex.
