### ISSUE TITLE
Error in mice(nhanes, method="myfunc") 

### ISSUE THREAD

**Issue by MarkusKonk** [stefvanbuuren/mice#53]
Dear @stefvanbuuren,

I tried to rerun the script you attached to the mice paper (https://www.jstatsoft.org/article/view/v045i03) in JStatSoft but ran into the following error in line 740 of the file v45i03.R: mice(nhanes, method="myfunc")
`Error in check.method(setup, data) : The following functions were not found: mice.impute.myfunc, mice.impute.myfunc, mice.impute.myfunc`

Do you have an idea?

Thanks in advance

Markus Konkol
http://o2r.info/
Institute for Geoinformatics
Münster, Germany

**Comment by stefvanbuuren** [comment]
You may create your own imputation method by defining a function whose name starts with `mice.impute.`, for example something like 

`mice.impute.myfunc <- function(y, ry, x, ...) {your code here}`

The `myfunc` part is just a placeholder, so `mice.impute.banana()` is also valid. Then `mice(..., method = "banana")` call will use `mice.impute.banana()` method instead of the standard function. Bottom line: you may evade this error by defining a function with the name `mice.impute.myfunc` in your active workspace.
