### ISSUE TITLE
Row order determines imputations 

### ISSUE THREAD

**Issue by jaspercooper** [stefvanbuuren/mice#58]
Let me start by saying I love this package, it's really wonderful software, thank you. Thought I'd bring something to your attention -- my colleague and I lost several hours of work to figuring this out so it certainly wasn't obvious to us, but apologies if this is a known issue.

We couldn't figure out why our replication archive had different imputations to our original, despite using near identical code, and setting seeds. 

It turns out the rows of our dataframes were in different order, and this changes the imputations, even for otherwise identical data. MWE below. Sorry I didn't have time to submit a PR. I suppose it has something to do with random sampling of data somewhere. Although setting `data.init` didn't seem to solve the problem. One solution may be to allow for an "id" argument that sorts data, does imputations, and puts it back into its original ordering? 

```r
library(mice)
set.seed(1234)
N <- 1000
data <- data.frame(
  X1 = sample(1:5, N, TRUE),
  X2 = sample(1:5, N, TRUE),
  X3 = sample(0:1, N, TRUE),
  X4 = sample(0:1, N, TRUE),
  id = 1:N
)
# 5% of values missing
missing <-
  matrix(data = sample(c(TRUE, FALSE), prod(dim(data)), TRUE, c(.05, .95)),
         nrow = nrow(data))
data[missing] <- NA
head(data)
tail(data)
colSums(is.na(data)) / nrow(data)
# reorder datasets
data_1 <- data[sample(data$id),]
data_2 <- data[sample(data$id),]
all(data_1 == data_2)
all(data_1$id %in% data_2$id)
# Show here that imputing the same dataset twice leads to same imputations
imputed_same_order_1 <- complete(mice(data = data, m = 1, seed = 1234))
imputed_same_order_2 <- complete(mice(data = data, m = 1, seed = 1234))
all(imputed_same_order_1 == imputed_same_order_2)
# Different order leads to different imputations
imputed_diff_order_1 <- complete(mice(data = data_1, m = 1, seed = 1234))
imputed_diff_order_2 <- complete(mice(data = data_2, m = 1, seed = 1234))
# Sort into same order
imputed_diff_order_1 <- imputed_diff_order_1[sort(imputed_diff_order_1$id), ]
imputed_diff_order_2 <- imputed_diff_order_2[sort(imputed_diff_order_2$id), ]
all(imputed_diff_order_1 == imputed_diff_order_2)
```

**Comment by stefvanbuuren** [comment]
Jasper, thanks for your mail.

It is possible to reproduce the imputations exactly ONLY IF the data and all analysis options are identical. Permuting the rows order (as you did), or permuting the column order will lead to different imputations. The good news, though, is that that the results will converge to the same estimates as for the original matrix as `m` gets larger. 

The reason is - as you suspected - that MICE needs to draw random values. By default, the first random value is used for the first missing value in the first column, the second random value is used for the second missing value in the first column, and so on. Changing the order of rows (or columns) will also change the value that is imputed for that cell, and hence the imputations will be different.

I think it is not very useful (and quite difficult, in fact) to try to get exact reproduction under permutation of rows or columns. If you want exact replication, there is no alternative but to use exactly the same data.

Hope this helps. Stef.
