### ISSUE TITLE
Multiple executions provide different outcomes -- Inconsistency of example of pg 92

### ISSUE THREAD

**Issue by Elesa** [stefvanbuuren/mice#65]
Hi,
I am using "mice" package to impute the missing values of a large dataset and I've noticed that multiple executions of mice() function generate significantly different outcomes. I tried to investigate whether that is ok or not and  noticed that in page 92 there is an example where two consecutive executions provide the same outcomes, more precisely:

imp1 <- mice(nhanes,maxit=1)
imp2 <- mice.mids(imp1)
# yields the same result as
imp <- mice(nhanes,maxit=2)
# for example:
#
# > imp$imp$bmi[1,]
# 1 2 3 4 5
# 1 30.1 35.3 33.2 35.3 27.5
# > imp2$imp$bmi[1,]
# 1 2 3 4 5
# 1 30.1 35.3 33.2 35.3 27.5

However, when I type the same commands I get 

> imp$imp$bmi[1,]
     1    2    3    4    5
1 29.6 28.7 29.6 29.6 22.5
> imp2$imp$bmi[1,]
     1    2    3    4    5
1 29.6 33.2 30.1 22.7 25.5

So  is the pdf documentation updated and if so can you please expla\in why I get different results -- though I've downloaded the latest version?

Thank you in advance!

Best,
Maria

**Comment by gerkovink** [comment]
Dear Maria,

The difference between your realisations stems from a difference in random seeds. If you fix the random number generator, the imputations are identical:

`imp1 <- mice(nhanes,maxit=1, seed=123)`
`imp2 <- mice.mids(imp1)`
`imp <- mice(nhanes,maxit=2, seed=123)`
`identical(imp2$imp$bmi, imp$imp$bmi)`

All the best, 

Gerko

**Comment by Elesa** [comment]
Dear Gerko,

Thank you very much for your prompt response!
I understand that fixing the random seed would also fix the outcomes but that is not what is suggested at the example of pg 92, which was the main reason why I mentioned that here.

Thanks again!

All the best,
Maria

**Comment by gerkovink** [comment]
Assuming that you refer to page 92 of the online manual: the example here points out that both approaches would yield the exact same result. So, instead of running two iterations from the start, one would obtain the exact same result if a single iteration is extended with `mice.mids()`. This is because `mice.mids` inherits the state of the random seed from the `mids` object. 

The pseudo code that is commented in the example, serves merely as a realisation where this would be true and the presented code from the example does not serve the purpose of yielding these results. However, I have changed the code in the example to

'imp1 <- mice(nhanes, maxit=1, seed = 123)`
'imp2 <- mice.mids(imp1)`
'# yields the same result as`
'imp <- mice(nhanes, maxit=2, seed = 123)`
'# verification`
'identical(imp$imp, imp2$imp)`

to avoid any confusion. These changes which will be pushed to `mice` in the next commit. 

Thanks, 

Gerko

**Comment by Elesa** [comment]
That was exactly my point :)
Thanks again!

Best wishes,
Maria
