### ISSUE TITLE
Empty method leaves missing values in imputed datasets

### ISSUE THREAD

**Issue by aneumann-science** [stefvanbuuren/mice#75]
Dear all,

When excluding a variable from imputation by specifying an empty method, mice 2.30 used to either give an error, that the variable is used for prediction, or run without issues. In 2.46, the imputation is performed, but variables still have missing values. Is this expected behavior, should the imputation be complete or should there be an error or warning?  

I have a dataset, which previously was imputed without issues in 2.30 and in 2.46 now only has about half of the rows completed, unless I use the default imputation method. This issue can be reproduced using the example dataset in 2.46, see below. A difference between the example and my dataset is, that nhanes will give an error in 2.30, but no error occured in my dataset and imputation was without issues. 

Example code in 2.46: 

```
 library(mice)

# Multiple imputation with chl excluded from imputation
imp <- mice(nhanes, method = c("","pmm","pmm",""))
table(is.na(complete(imp)))

FALSE  TRUE 
   76    24 
```

**Comment by stefvanbuuren** [comment]
This is expected behaviour, and a consequence of the new `where` facility. Your specification does not impute `chl`, and `mice` will now propagate the missings in the predictors to the target variable, and hence we now find missings also in `bmi` and `hyp` for those rows with missing values in `chl`. 

If, in addition, you remove `chl` as predictor, then all cells of `bmi` and `hyp` will be imputed.

I don't think it is necessary to create a warning. This is just how it works now.
