### ISSUE TITLE
Error when imputing with predictor matrix after update on mice 3.0.0

### ISSUE THREAD

**Issue by uweremerbollow** [stefvanbuuren/mice#96]
Hi!

I use R 3.5 andf mice 3.0.0 to impute a subset of variables in my data based on a subset of variables.(these variables are all numeric). I create a predictor matrix and impute like this (reproducible example with nhanes):
```
predMatrix <- matrix(rep(0, 4*4), ncol=4)
predMatrix[c(1:2), c(1:2, 4)] <- 1
diag(predMatrix) <- 0 
nhanes.miced <- mice(nhanes, m=30, maxit=30, predictorMatrix = predMatrix, seed=2016)
```

This approach worked well. After updating mice to v 3.0.0 along with a number of other packages I get a strange error:
```
Error in reformulate(setdiff(vars, j), response = j) : 
'termlabels' must be a character vector of length at least one
```

When I switch back to mice version 2.3, the error changes to. 
```
Error in .subset(x, j) : invalid subscript type 'list'
```
But the code was executable with mice 2.3. Could the problem stem from a package that was also updated and which mice is depending on? Sadly, I have no idea which (other) packages were updated from which version.

I would appreciate any hint, 
kind regards, Uwe Remer

University of Stuttgart
Institute for Social Sciences

**Comment by gerkovink** [comment]
Dear Uwe, 

I think the error you see is the same as mentioned in #93. This problem has since been fixed and the error should be gone if you install the latest version of mice cf. 

`install.packages("devtools")`
`devtools::install_github(repo = "stefvanbuuren/mice")`

Please let us know if the problem persists. 

All the best, 

Gerko

**Comment by gerkovink** [comment]
I see the problem still persists in `mice 3.0.8`. Will look into it.

**Comment by gerkovink** [comment]
Dear Uwe, 

Your `predictorMatrix` specifies that only `age` [completely observed] and `bmi` should be imputed. However, no predictor relations are set for the incomplete variables `hyp` and `chol`. That is where the error stems from. By simply setting the imputation method to `""` for those variables that are incomplete, but should not be imputed conform your predictor matrix, the problem goes away - but the incomplete variables do not play a role as predictors because they are not completely observed. 

It will be nicer to solve this problem within the algorithm. I will look into this. 

In the meanwhile, here is a code example that solves the error you receive:

```
pred <- make.predictorMatrix(nhanes)
pred[, "hyp"] <- 0
pred[c("hyp", "chl"), ] <- 0
meth <- c("", "pmm", "", "")
nhanes.miced <- mice(nhanes, m=30, maxit=30, 
                     method = meth,
                     predictorMatrix = pred, 
                     seed=2016)
```

**Comment by gerkovink** [comment]
@stefvanbuuren  Is this expected behaviour?

**Comment by stefvanbuuren** [comment]
Not intended behaviour, so we should fix this. One way is to would be to specify "" as method, but it would be better if `reformulate()` could handle situations without predictors.

**Comment by gerkovink** [comment]
Agreed. Will look into it.

**Comment by uweremerbollow** [comment]
Thank you @gerkovink, your suggestion to explicitly set the empty method did it.
